name: 👾 validate links

on: [push, pull_request]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: install awesome_bot
        run: gem install awesome_bot

      - name: validate URLs
        run: awesome_bot README.md --allow-redirect --request-delay 0.4
